"""Initial migration for asset tracker schema

Revision ID: 0a0ada48a120
Revises: 
Create Date: 2025-07-15 18:38:35.784900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0ada48a120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturing_challenges',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('challenge_category', sa.String(length=255), nullable=False),
    sa.Column('challenge_name', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('challenge_id'),
    sa.UniqueConstraint('challenge_name')
    )
    op.create_index(op.f('ix_manufacturing_challenges_challenge_category'), 'manufacturing_challenges', ['challenge_category'], unique=False)
    op.create_table('manufacturing_technologies',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('technology_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('technology_id'),
    sa.UniqueConstraint('technology_name')
    )
    op.create_table('partners',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('partner_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('base_technology', sa.String(length=255), nullable=True),
    sa.Column('mechanism_of_action', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('indications',
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('indication_name', sa.String(length=255), nullable=False),
    sa.Column('therapeutic_area', sa.String(length=255), nullable=True),
    sa.Column('development_phase', sa.String(length=100), nullable=True),
    sa.Column('expected_launch_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('indication_id')
    )
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(length=255), nullable=True),
    sa.Column('anthropic_api_key', sa.String(length=255), nullable=True),
    sa.Column('google_api_key', sa.String(length=255), nullable=True),
    sa.Column('ollama_base_url', sa.String(length=255), nullable=True),
    sa.Column('apollo_client_id', sa.String(length=255), nullable=True),
    sa.Column('apollo_client_secret', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('product_supply_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('manufacturing_stage', sa.String(length=255), nullable=False),
    sa.Column('supply_model', sa.String(length=100), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('internal_site_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_to_challenge',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['manufacturing_challenges.challenge_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'challenge_id')
    )
    op.create_table('product_to_technology',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['manufacturing_technologies.technology_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'technology_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_to_technology')
    op.drop_table('product_to_challenge')
    op.drop_table('product_supply_chain')
    op.drop_table('llm_settings')
    op.drop_table('indications')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_table('products')
    op.drop_table('partners')
    op.drop_table('manufacturing_technologies')
    op.drop_index(op.f('ix_manufacturing_challenges_challenge_category'), table_name='manufacturing_challenges')
    op.drop_table('manufacturing_challenges')
    # ### end Alembic commands ###
