"""Create tables

Revision ID: 1748b802796a
Revises: 001_initial
Create Date: 2025-12-16 17:09:23.519558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1748b802796a'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agnostic_description', sa.Text(), nullable=True),
    sa.Column('agnostic_root_cause', sa.Text(), nullable=True),
    sa.Column('value_step', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manufacturing_capabilities',
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('capability_name', sa.String(length=255), nullable=False),
    sa.Column('capability_category', sa.String(length=255), nullable=True),
    sa.Column('approach_category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complexity_weight', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('capability_id'),
    sa.UniqueConstraint('capability_name')
    )
    op.create_index(op.f('ix_manufacturing_capabilities_capability_category'), 'manufacturing_capabilities', ['capability_category'], unique=False)
    op.create_table('manufacturing_entities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('operational_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_manufacturing_entities_entity_type'), 'manufacturing_entities', ['entity_type'], unique=False)
    op.create_table('modalities',
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('modality_name', sa.String(length=255), nullable=False),
    sa.Column('modality_category', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('modality_id'),
    sa.UniqueConstraint('modality_name')
    )
    op.create_table('process_stages',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('stage_category', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_stage_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_stage_id'], ['process_stages.stage_id'], ),
    sa.PrimaryKeyConstraint('stage_id'),
    sa.UniqueConstraint('stage_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('challenge_modality_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('specific_description', sa.Text(), nullable=True),
    sa.Column('specific_root_cause', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('impact_details', sa.Text(), nullable=True),
    sa.Column('maturity_score', sa.Integer(), nullable=True),
    sa.Column('maturity_details', sa.Text(), nullable=True),
    sa.Column('trends_3_5_years', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.modality_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'modality_id', name='uq_challenge_modality')
    )
    op.create_table('entity_capabilities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('capability_level', sa.String(length=100), nullable=True),
    sa.Column('implementation_date', sa.Date(), nullable=True),
    sa.Column('upgrade_planned', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['manufacturing_capabilities.capability_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'capability_id')
    )
    op.create_table('external_partners',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('contract_terms', sa.Text(), nullable=True),
    sa.Column('exclusivity_level', sa.String(length=100), nullable=True),
    sa.Column('capacity_allocation', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('internal_facilities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=100), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('compatible_product_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('internal_capacity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.String(length=255), nullable=True),
    sa.Column('anthropic_api_key', sa.String(length=255), nullable=True),
    sa.Column('google_api_key', sa.String(length=255), nullable=True),
    sa.Column('ollama_base_url', sa.String(length=255), nullable=True),
    sa.Column('apollo_client_id', sa.String(length=255), nullable=True),
    sa.Column('apollo_client_secret', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('modality_requirements',
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('required_capability_id', sa.Integer(), nullable=False),
    sa.Column('requirement_level', sa.String(length=100), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('timeline_context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.modality_id'], ),
    sa.ForeignKeyConstraint(['required_capability_id'], ['manufacturing_capabilities.capability_id'], ),
    sa.PrimaryKeyConstraint('modality_id', 'required_capability_id')
    )
    op.create_table('process_templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.modality_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('is_nme', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_line_extension', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=True),
    sa.Column('launch_sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('line_extension_indication', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_technology', sa.String(length=255), nullable=True),
    sa.Column('mechanism_of_action', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.String(length=255), nullable=True),
    sa.Column('therapeutic_area', sa.String(length=255), nullable=True),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('project_status', sa.String(length=100), nullable=True),
    sa.Column('lead_indication', sa.String(length=255), nullable=True),
    sa.Column('expected_launch_year', sa.Integer(), nullable=True),
    sa.Column('lifecycle_indications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regulatory_designations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manufacturing_strategy', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_sites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('volume_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_packaging', sa.String(length=100), nullable=True),
    sa.Column('route_of_administration', sa.String(length=100), nullable=True),
    sa.Column('biel_category', sa.String(length=20), nullable=True),
    sa.Column('granulation_technology', sa.String(length=255), nullable=True),
    sa.Column('submission_status', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('launch_geography', sa.String(length=255), nullable=True),
    sa.Column('regulatory_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ppq_status', sa.String(length=100), nullable=True),
    sa.Column('ppq_completion_date', sa.Date(), nullable=True),
    sa.Column('ppq_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline_variance_days', sa.Integer(), nullable=True),
    sa.Column('timeline_variance_baseline', sa.String(length=50), nullable=True),
    sa.Column('critical_path_item', sa.String(length=255), nullable=True),
    sa.Column('ds_volume_category', sa.String(length=100), nullable=True),
    sa.Column('dp_volume_category', sa.String(length=100), nullable=True),
    sa.Column('ds_suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dp_suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_partners', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('operational_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supply_chain_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_trials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_population', sa.Text(), nullable=True),
    sa.Column('development_program_name', sa.String(length=255), nullable=True),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.Column('process_template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.modality_id'], ),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_template_id'], ['process_templates.template_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_current_phase'), 'products', ['current_phase'], unique=False)
    op.create_index(op.f('ix_products_parent_product_id'), 'products', ['parent_product_id'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_index(op.f('ix_products_project_status'), 'products', ['project_status'], unique=False)
    op.create_index(op.f('ix_products_therapeutic_area'), 'products', ['therapeutic_area'], unique=False)
    op.create_table('template_stages',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('base_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['process_stages.stage_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['process_templates.template_id'], ),
    sa.PrimaryKeyConstraint('template_id', 'stage_id')
    )
    op.create_table('indications',
    sa.Column('indication_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('indication_name', sa.String(length=255), nullable=False),
    sa.Column('therapeutic_area', sa.String(length=255), nullable=True),
    sa.Column('development_phase', sa.String(length=100), nullable=True),
    sa.Column('expected_launch_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('indication_id')
    )
    op.create_table('product_manufacturing_suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supply_type', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('site_location', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('qualification_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('product_process_overrides',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('override_type', sa.String(length=50), nullable=True),
    sa.Column('additional_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['process_stages.stage_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'stage_id')
    )
    op.create_table('product_regulatory_filings',
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('indication', sa.String(length=255), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=False),
    sa.Column('filing_type', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('designations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regulatory_authority', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('filing_id')
    )
    op.create_table('product_requirements',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('required_capability_id', sa.Integer(), nullable=False),
    sa.Column('requirement_level', sa.String(length=100), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('timeline_needed', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['required_capability_id'], ['manufacturing_capabilities.capability_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'required_capability_id')
    )
    op.create_table('product_supply_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('manufacturing_stage', sa.String(length=255), nullable=False),
    sa.Column('supply_model', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('internal_site_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_timelines',
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.String(length=100), nullable=False),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('variance_days', sa.Integer(), nullable=True),
    sa.Column('baseline_plan', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('timeline_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_timelines')
    op.drop_table('product_supply_chain')
    op.drop_table('product_requirements')
    op.drop_table('product_regulatory_filings')
    op.drop_table('product_process_overrides')
    op.drop_table('product_manufacturing_suppliers')
    op.drop_table('indications')
    op.drop_table('template_stages')
    op.drop_index(op.f('ix_products_therapeutic_area'), table_name='products')
    op.drop_index(op.f('ix_products_project_status'), table_name='products')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_parent_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_current_phase'), table_name='products')
    op.drop_table('products')
    op.drop_table('process_templates')
    op.drop_table('modality_requirements')
    op.drop_table('llm_settings')
    op.drop_table('internal_facilities')
    op.drop_table('external_partners')
    op.drop_table('entity_capabilities')
    op.drop_table('challenge_modality_details')
    op.drop_table('users')
    op.drop_table('process_stages')
    op.drop_table('modalities')
    op.drop_index(op.f('ix_manufacturing_entities_entity_type'), table_name='manufacturing_entities')
    op.drop_table('manufacturing_entities')
    op.drop_index(op.f('ix_manufacturing_capabilities_capability_category'), table_name='manufacturing_capabilities')
    op.drop_table('manufacturing_capabilities')
    op.drop_table('challenges')
    # ### end Alembic commands ###
