"""Add short_description fields to various models

Revision ID: 1a2b3c4d5e6f
Revises: f9d8e7c6b5a4
Create Date: 2025-07-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = 'f9d8e7c6b5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturing_challenges', sa.Column('short_description', sa.String(length=255), nullable=True))
    op.add_column('manufacturing_technologies', sa.Column('short_description', sa.String(length=255), nullable=True))
    op.add_column('modalities', sa.Column('short_description', sa.String(length=255), nullable=True))
    op.add_column('process_stages', sa.Column('short_description', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('short_description', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'short_description')
    op.drop_column('process_stages', 'short_description')
    op.drop_column('modalities', 'short_description')
    op.drop_column('manufacturing_technologies', 'short_description')
    op.drop_column('manufacturing_challenges', 'short_description')
    # ### end Alembic commands ###