"""Link challenges to process stages

Revision ID: 3c4d5e6f7g8h
Revises: 2b3c4d5e6f7g
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4d5e6f7g8h'
down_revision = '2b3c4d5e6f7g' 
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add primary_stage_id to manufacturing_challenges
    op.add_column('manufacturing_challenges', 
                  sa.Column('primary_stage_id', sa.Integer(), nullable=True))
    
    # Add severity_level to help classify challenge impact
    op.add_column('manufacturing_challenges',
                  sa.Column('severity_level', sa.String(length=50), nullable=True))
    
    # Create foreign key constraint to process_stages
    op.create_foreign_key('fk_challenges_primary_stage_id',
                         'manufacturing_challenges',
                         'process_stages',
                         ['primary_stage_id'],
                         ['stage_id'])
    
    # Create index for performance
    op.create_index('idx_challenges_stage_lookup',
                   'manufacturing_challenges',
                   ['primary_stage_id'],
                   unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop index
    op.drop_index('idx_challenges_stage_lookup', table_name='manufacturing_challenges')
    
    # Drop foreign key constraint
    op.drop_constraint('fk_challenges_primary_stage_id',
                      'manufacturing_challenges',
                      type_='foreignkey')
    
    # Drop columns
    op.drop_column('manufacturing_challenges', 'severity_level')
    op.drop_column('manufacturing_challenges', 'primary_stage_id')
    
    # ### end Alembic commands ###