"""Add hierarchical structure to process stages

Revision ID: 4d5e6f7g8h9i
Revises: 3c4d5e6f7g8h
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5e6f7g8h9i'
down_revision = '3c4d5e6f7g8h'  # Update this to your latest migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add hierarchy support columns
    op.add_column('process_stages',
                  sa.Column('parent_stage_id', sa.Integer(), nullable=True))
    
    op.add_column('process_stages',
                  sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    
    op.add_column('process_stages',
                  sa.Column('stage_order', sa.Integer(), nullable=True))
    
    # Create self-referential foreign key
    op.create_foreign_key('fk_stages_parent_stage_id',
                         'process_stages',
                         'process_stages',
                         ['parent_stage_id'],
                         ['stage_id'])
    
    # Create indexes for performance
    op.create_index('idx_stages_hierarchy_lookup',
                   'process_stages',
                   ['parent_stage_id', 'hierarchy_level'],
                   unique=False)
    
    op.create_index('idx_stages_level',
                   'process_stages',
                   ['hierarchy_level'],
                   unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_stages_level', table_name='process_stages')
    op.drop_index('idx_stages_hierarchy_lookup', table_name='process_stages')
    
    # Drop foreign key
    op.drop_constraint('fk_stages_parent_stage_id',
                      'process_stages',
                      type_='foreignkey')
    
    # Drop columns
    op.drop_column('process_stages', 'stage_order')
    op.drop_column('process_stages', 'hierarchy_level')
    op.drop_column('process_stages', 'parent_stage_id')
    
    # ### end Alembic commands ###