"""Add system_prompt to user model

Revision ID: 5e7f8g9h0i1j
Revises: f9d8e7c6b5a4
Create Date: 2025-09-23 08:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7f8g9h0i1j'
down_revision = 'f9d8e7c6b5a4' # This should be the ID of the previous migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('system_prompt')
    # ### end Alembic commands ###