"""Add status field to Project model

Revision ID: 859958f3ac20
Revises: 004_core_entities
Create Date: 2026-02-05 14:06:43.154790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859958f3ac20'
down_revision = '004_core_entities'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_drug_products_code'), 'drug_products', type_='unique')
    op.drop_index(op.f('ix_drug_products_code'), table_name='drug_products')
    op.create_index(op.f('ix_drug_products_code'), 'drug_products', ['code'], unique=True)
    op.drop_index(op.f('ix_drug_substances_inn'), table_name='drug_substances')
    op.drop_constraint(op.f('uq_drug_substances_code'), 'drug_substances', type_='unique')
    op.drop_index(op.f('ix_drug_substances_code'), table_name='drug_substances')
    op.create_index(op.f('ix_drug_substances_code'), 'drug_substances', ['code'], unique=True)
    op.add_column('projects', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_projects_indication'), table_name='projects')
    op.drop_index(op.f('ix_projects_launch'), table_name='projects')
    op.drop_constraint(op.f('uq_projects_name'), 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_projects_name'), 'projects', ['name'])
    op.create_index(op.f('ix_projects_launch'), 'projects', ['launch'], unique=False)
    op.create_index(op.f('ix_projects_indication'), 'projects', ['indication'], unique=False)
    op.drop_column('projects', 'status')
    op.drop_index(op.f('ix_drug_substances_code'), table_name='drug_substances')
    op.create_index(op.f('ix_drug_substances_code'), 'drug_substances', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_drug_substances_code'), 'drug_substances', ['code'])
    op.create_index(op.f('ix_drug_substances_inn'), 'drug_substances', ['inn'], unique=False)
    op.drop_index(op.f('ix_drug_products_code'), table_name='drug_products')
    op.create_index(op.f('ix_drug_products_code'), 'drug_products', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_drug_products_code'), 'drug_products', ['code'])
    # ### end Alembic commands ###
