"""add_requirements_and_entity_details

Revision ID: a1b2c3d4e5f6
Revises: e4a2c1b9d0f8
Create Date: 2025-07-16 11:00:20.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e4a2c1b9d0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Requirements tables
    op.create_table('modality_requirements',
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('required_capability_id', sa.Integer(), nullable=False),
    sa.Column('requirement_level', sa.String(length=100), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('timeline_context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.modality_id'], ),
    sa.ForeignKeyConstraint(['required_capability_id'], ['manufacturing_capabilities.capability_id'], ),
    sa.PrimaryKeyConstraint('modality_id', 'required_capability_id')
    )
    op.create_table('product_requirements',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('required_capability_id', sa.Integer(), nullable=False),
    sa.Column('requirement_level', sa.String(length=100), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('timeline_needed', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['required_capability_id'], ['manufacturing_capabilities.capability_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'required_capability_id')
    )

    # Entity details tables (using shared primary key for 1-to-1)
    op.create_table('internal_facilities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=100), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('compatible_product_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('internal_capacity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('external_partners',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('contract_terms', sa.Text(), nullable=True),
    sa.Column('exclusivity_level', sa.String(length=100), nullable=True),
    sa.Column('capacity_allocation', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )

    # Entity capabilities junction table
    op.create_table('entity_capabilities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('capability_level', sa.String(length=100), nullable=True),
    sa.Column('implementation_date', sa.Date(), nullable=True),
    sa.Column('upgrade_planned', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capability_id'], ['manufacturing_capabilities.capability_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['manufacturing_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'capability_id')
    )

    # Update product_supply_chain table
    op.add_column('product_supply_chain', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_supply_chain_entity_id', 'product_supply_chain', 'manufacturing_entities', ['entity_id'], ['entity_id'])
    op.drop_constraint('product_supply_chain_partner_id_fkey', 'product_supply_chain', type_='foreignkey')
    op.drop_column('product_supply_chain', 'partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert product_supply_chain table changes
    op.add_column('product_supply_chain', sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_supply_chain_partner_id_fkey', 'product_supply_chain', 'partners', ['partner_id'], ['partner_id'])
    op.drop_constraint('fk_supply_chain_entity_id', 'product_supply_chain', type_='foreignkey')
    op.drop_column('product_supply_chain', 'entity_id')

    # Drop all new tables
    op.drop_table('entity_capabilities')
    op.drop_table('external_partners')
    op.drop_table('internal_facilities')
    op.drop_table('product_requirements')
    op.drop_table('modality_requirements')
    # ### end Alembic commands ###