"""Add detailed product fields

Revision ID: d8a6a3bc9397
Revises: 0a0ada48a120
Create Date: 2025-07-15 19:29:19.336138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8a6a3bc9397'
down_revision = '0a0ada48a120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('therapeutic_area', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('current_phase', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('project_status', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('lead_indication', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('expected_launch_year', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('lifecycle_indications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('regulatory_designations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('manufacturing_strategy', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('manufacturing_sites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('volume_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_products_current_phase'), 'products', ['current_phase'], unique=False)
    op.create_index(op.f('ix_products_project_status'), 'products', ['project_status'], unique=False)
    op.create_index(op.f('ix_products_therapeutic_area'), 'products', ['therapeutic_area'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_therapeutic_area'), table_name='products')
    op.drop_index(op.f('ix_products_project_status'), table_name='products')
    op.drop_index(op.f('ix_products_current_phase'), table_name='products')
    op.drop_column('products', 'volume_forecast')
    op.drop_column('products', 'manufacturing_sites')
    op.drop_column('products', 'manufacturing_strategy')
    op.drop_column('products', 'regulatory_designations')
    op.drop_column('products', 'lifecycle_indications')
    op.drop_column('products', 'expected_launch_year')
    op.drop_column('products', 'lead_indication')
    op.drop_column('products', 'project_status')
    op.drop_column('products', 'current_phase')
    op.drop_column('products', 'therapeutic_area')
    # ### end Alembic commands ###
