"""Add operational tracking tables and fields

Revision ID: de1790bb1890
Revises: 2e7edcb6b186
Create Date: 2025-09-24 06:05:28.871846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de1790bb1890'
down_revision = '2e7edcb6b186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ==================== CREATE ONLY OUR NEW TABLES ====================
    # Remove the problematic view tables that already exist
    
    op.create_table('product_manufacturing_suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supply_type', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('site_location', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('qualification_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    
    op.create_table('product_regulatory_filings',
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('indication', sa.String(length=255), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=False),
    sa.Column('filing_type', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('designations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regulatory_authority', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('filing_id')
    )
    
    op.create_table('product_timelines',
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.String(length=100), nullable=False),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('variance_days', sa.Integer(), nullable=True),
    sa.Column('baseline_plan', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('timeline_id')
    )
    
    # ==================== INDEX CHANGES ====================
    # Keep the index changes that don't cause issues
    try:
        op.drop_index(op.f('idx_entity_capabilities_lookup'), table_name='entity_capabilities')
    except:
        pass  # Ignore if index doesn't exist
        
    try:
        op.drop_index(op.f('idx_capabilities_category'), table_name='manufacturing_capabilities')
        op.create_index(op.f('ix_manufacturing_capabilities_capability_category'), 'manufacturing_capabilities', ['capability_category'], unique=False)
    except:
        pass  # Ignore if index doesn't exist
        
    try:
        op.drop_index(op.f('idx_challenges_stage_lookup'), table_name='manufacturing_challenges')
    except:
        pass  # Ignore if index doesn't exist
        
    try:
        op.drop_index(op.f('idx_entities_type'), table_name='manufacturing_entities')
        op.create_index(op.f('ix_manufacturing_entities_entity_type'), 'manufacturing_entities', ['entity_type'], unique=False)
    except:
        pass  # Ignore if index doesn't exist
        
    try:
        op.drop_index(op.f('idx_stages_hierarchy_lookup'), table_name='process_stages')
    except:
        pass  # Ignore if index doesn't exist
        
    try:
        op.drop_index(op.f('idx_stages_level'), table_name='process_stages')
    except:
        pass  # Ignore if index doesn't exist
    
    # ==================== ADD PRODUCT COLUMNS ====================
    op.add_column('products', sa.Column('primary_packaging', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('route_of_administration', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('biel_category', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('granulation_technology', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('submission_status', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('submission_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('approval_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('launch_geography', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('regulatory_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('ppq_status', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('ppq_completion_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('ppq_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('timeline_variance_days', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('timeline_variance_baseline', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('critical_path_item', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('ds_volume_category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('dp_volume_category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('ds_suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('dp_suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('device_partners', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('operational_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('timeline_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('supply_chain_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('clinical_trials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('patient_population', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('development_program_name', sa.String(length=255), nullable=True))
    
    try:
        op.drop_index(op.f('idx_products_modality'), table_name='products')
    except:
        pass  # Ignore if index doesn't exist
        
    try:
        op.drop_index(op.f('idx_template_stages_lookup'), table_name='template_stages')
    except:
        pass  # Ignore if index doesn't exist
    
    # Remove the problematic table drops/creates
    # We're NOT touching partners table or the view tables
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ==================== REVERSE INDEX CHANGES ====================
    try:
        op.create_index(op.f('idx_template_stages_lookup'), 'template_stages', ['template_id', 'stage_id'], unique=False)
    except:
        pass
        
    try:
        op.create_index(op.f('idx_products_modality'), 'products', ['modality_id'], unique=False)
    except:
        pass
    
    # ==================== REMOVE PRODUCT COLUMNS ====================
    op.drop_column('products', 'development_program_name')
    op.drop_column('products', 'patient_population')
    op.drop_column('products', 'clinical_trials')
    op.drop_column('products', 'supply_chain_risks')
    op.drop_column('products', 'timeline_risks')
    op.drop_column('products', 'operational_risks')
    op.drop_column('products', 'device_partners')
    op.drop_column('products', 'dp_suppliers')
    op.drop_column('products', 'ds_suppliers')
    op.drop_column('products', 'dp_volume_category')
    op.drop_column('products', 'ds_volume_category')
    op.drop_column('products', 'critical_path_item')
    op.drop_column('products', 'timeline_variance_baseline')
    op.drop_column('products', 'timeline_variance_days')
    op.drop_column('products', 'ppq_details')
    op.drop_column('products', 'ppq_completion_date')
    op.drop_column('products', 'ppq_status')
    op.drop_column('products', 'regulatory_details')
    op.drop_column('products', 'launch_geography')
    op.drop_column('products', 'approval_date')
    op.drop_column('products', 'submission_date')
    op.drop_column('products', 'submission_status')
    op.drop_column('products', 'granulation_technology')
    op.drop_column('products', 'biel_category')
    op.drop_column('products', 'route_of_administration')
    op.drop_column('products', 'primary_packaging')
    
    # ==================== REVERSE INDEX CHANGES ====================
    try:
        op.create_index(op.f('idx_stages_level'), 'process_stages', ['hierarchy_level'], unique=False)
    except:
        pass
        
    try:
        op.create_index(op.f('idx_stages_hierarchy_lookup'), 'process_stages', ['parent_stage_id', 'hierarchy_level'], unique=False)
    except:
        pass
        
    try:
        op.drop_index(op.f('ix_manufacturing_entities_entity_type'), table_name='manufacturing_entities')
        op.create_index(op.f('idx_entities_type'), 'manufacturing_entities', ['entity_type'], unique=False)
    except:
        pass
        
    try:
        op.create_index(op.f('idx_challenges_stage_lookup'), 'manufacturing_challenges', ['primary_stage_id'], unique=False)
    except:
        pass
        
    try:
        op.drop_index(op.f('ix_manufacturing_capabilities_capability_category'), table_name='manufacturing_capabilities')
        op.create_index(op.f('idx_capabilities_category'), 'manufacturing_capabilities', ['capability_category'], unique=False)
    except:
        pass
        
    try:
        op.create_index(op.f('idx_entity_capabilities_lookup'), 'entity_capabilities', ['entity_id', 'capability_id'], unique=False)
    except:
        pass
    
    # ==================== DROP ONLY OUR NEW TABLES ====================
    op.drop_table('product_timelines')
    op.drop_table('product_regulatory_filings')
    op.drop_table('product_manufacturing_suppliers')
    
    # We're NOT recreating the partners table or the view tables
    # ### end Alembic commands ###