"""add_modalities_and_capabilities_tables

Revision ID: e4a2c1b9d0f8
Revises: d8a6a3bc9397
Create Date: 2025-07-16 10:30:15.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4a2c1b9d0f8'
down_revision = 'd8a6a3bc9397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create modalities table
    op.create_table('modalities',
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('modality_name', sa.String(length=255), nullable=False),
    sa.Column('modality_category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard_challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('modality_id'),
    sa.UniqueConstraint('modality_name')
    )

    # Create manufacturing_capabilities table
    op.create_table('manufacturing_capabilities',
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('capability_name', sa.String(length=255), nullable=False),
    sa.Column('capability_category', sa.String(length=255), nullable=True),
    sa.Column('approach_category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complexity_weight', sa.Integer(), nullable=True, server_default='1'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('capability_id'),
    sa.UniqueConstraint('capability_name')
    )
    op.create_index(op.f('idx_capabilities_category'), 'manufacturing_capabilities', ['capability_category'], unique=False)

    # Create manufacturing_entities base table
    op.create_table('manufacturing_entities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('operational_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('idx_entities_type'), 'manufacturing_entities', ['entity_type'], unique=False)

    # Add modality link to products
    op.add_column('products', sa.Column('modality_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_products_modality_id', 'products', 'modalities', ['modality_id'], ['modality_id'])
    op.create_index(op.f('idx_products_modality'), 'products', ['modality_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_products_modality'), table_name='products')
    op.drop_constraint('fk_products_modality_id', 'products', type_='foreignkey')
    op.drop_column('products', 'modality_id')
    
    op.drop_index(op.f('idx_entities_type'), table_name='manufacturing_entities')
    op.drop_table('manufacturing_entities')
    
    op.drop_index(op.f('idx_capabilities_category'), table_name='manufacturing_capabilities')
    op.drop_table('manufacturing_capabilities')

    op.drop_table('modalities')
    # ### end Alembic commands ###