"""add nme line extension fields

Revision ID: e98f0b35fdc0
Revises: f521ade2ab3d
Create Date: 2025-11-07 10:52:26.524969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98f0b35fdc0'
down_revision = 'f521ade2ab3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_nme', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('products', sa.Column('is_line_extension', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('parent_product_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('launch_sequence', sa.Integer(), server_default='1', nullable=False))
    op.add_column('products', sa.Column('line_extension_indication', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_products_parent_product_id'), 'products', ['parent_product_id'], unique=False)
    op.create_foreign_key(None, 'products', 'products', ['parent_product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_technology_modalities_mod'), table_name='technology_modalities')
    op.drop_index(op.f('idx_technology_modalities_tech'), table_name='technology_modalities')
    op.drop_constraint(op.f('technology_modalities_modality_id_fkey'), 'technology_modalities', type_='foreignkey')
    op.drop_constraint(op.f('technology_modalities_technology_id_fkey'), 'technology_modalities', type_='foreignkey')
    op.create_foreign_key(None, 'technology_modalities', 'manufacturing_technologies', ['technology_id'], ['technology_id'])
    op.create_foreign_key(None, 'technology_modalities', 'modalities', ['modality_id'], ['modality_id'])
    op.create_index('ix_products_is_nme', 'products', ['is_nme'], unique=False)
    op.create_index('ix_products_launch_sequence', 'products', ['parent_product_id', 'launch_sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technology_modalities', type_='foreignkey')
    op.drop_constraint(None, 'technology_modalities', type_='foreignkey')
    op.create_foreign_key(op.f('technology_modalities_technology_id_fkey'), 'technology_modalities', 'manufacturing_technologies', ['technology_id'], ['technology_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('technology_modalities_modality_id_fkey'), 'technology_modalities', 'modalities', ['modality_id'], ['modality_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_technology_modalities_tech'), 'technology_modalities', ['technology_id'], unique=False)
    op.create_index(op.f('idx_technology_modalities_mod'), 'technology_modalities', ['modality_id'], unique=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index('ix_products_launch_sequence', table_name='products')
    op.drop_index('ix_products_is_nme', table_name='products')
    op.drop_index(op.f('ix_products_parent_product_id'), table_name='products')
    op.drop_column('products', 'line_extension_indication')
    op.drop_column('products', 'launch_sequence')
    op.drop_column('products', 'parent_product_id')
    op.drop_column('products', 'is_line_extension')
    op.drop_column('products', 'is_nme')
    # ### end Alembic commands ###
