"""Add modality_id and template_id to manufacturing_technologies

Revision ID: f2ddc3525b42
Revises: c19e20288615
Create Date: 2025-10-13 12:58:36.997047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ddc3525b42'
down_revision = 'c19e20288615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partners')
    op.add_column('manufacturing_technologies', sa.Column('modality_id', sa.Integer(), nullable=True))
    op.add_column('manufacturing_technologies', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('manufacturing_technologies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('manufacturing_technologies', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_manufacturing_technologies_modality_id'), 'manufacturing_technologies', ['modality_id'], unique=False)
    op.create_index(op.f('ix_manufacturing_technologies_stage_id'), 'manufacturing_technologies', ['stage_id'], unique=False)
    op.create_index(op.f('ix_manufacturing_technologies_template_id'), 'manufacturing_technologies', ['template_id'], unique=False)
    op.create_foreign_key(None, 'manufacturing_technologies', 'process_templates', ['template_id'], ['template_id'])
    op.create_foreign_key(None, 'manufacturing_technologies', 'modalities', ['modality_id'], ['modality_id'])
    op.drop_index(op.f('idx_modality_challenges_challenge'), table_name='modality_challenges')
    op.drop_index(op.f('idx_modality_challenges_modality'), table_name='modality_challenges')
    op.drop_constraint(op.f('modality_challenges_challenge_id_fkey'), 'modality_challenges', type_='foreignkey')
    op.drop_constraint(op.f('modality_challenges_modality_id_fkey'), 'modality_challenges', type_='foreignkey')
    op.create_foreign_key(None, 'modality_challenges', 'manufacturing_challenges', ['challenge_id'], ['challenge_id'])
    op.create_foreign_key(None, 'modality_challenges', 'modalities', ['modality_id'], ['modality_id'])
    op.drop_index(op.f('idx_product_challenge_type'), table_name='product_to_challenge')
    op.drop_index(op.f('ix_products_process_template_id'), table_name='products')
    op.drop_constraint(op.f('fk_products_process_template_id'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'process_templates', ['process_template_id'], ['template_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_process_template_id'), 'products', 'process_templates', ['process_template_id'], ['template_id'], ondelete='SET NULL')
    op.create_index(op.f('ix_products_process_template_id'), 'products', ['process_template_id'], unique=False)
    op.create_index(op.f('idx_product_challenge_type'), 'product_to_challenge', ['product_id', 'relationship_type'], unique=False)
    op.drop_constraint(None, 'modality_challenges', type_='foreignkey')
    op.drop_constraint(None, 'modality_challenges', type_='foreignkey')
    op.create_foreign_key(op.f('modality_challenges_modality_id_fkey'), 'modality_challenges', 'modalities', ['modality_id'], ['modality_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('modality_challenges_challenge_id_fkey'), 'modality_challenges', 'manufacturing_challenges', ['challenge_id'], ['challenge_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_modality_challenges_modality'), 'modality_challenges', ['modality_id'], unique=False)
    op.create_index(op.f('idx_modality_challenges_challenge'), 'modality_challenges', ['challenge_id'], unique=False)
    op.drop_constraint(None, 'manufacturing_technologies', type_='foreignkey')
    op.drop_constraint(None, 'manufacturing_technologies', type_='foreignkey')
    op.drop_index(op.f('ix_manufacturing_technologies_template_id'), table_name='manufacturing_technologies')
    op.drop_index(op.f('ix_manufacturing_technologies_stage_id'), table_name='manufacturing_technologies')
    op.drop_index(op.f('ix_manufacturing_technologies_modality_id'), table_name='manufacturing_technologies')
    op.alter_column('manufacturing_technologies', 'stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('manufacturing_technologies', 'created_at')
    op.drop_column('manufacturing_technologies', 'template_id')
    op.drop_column('manufacturing_technologies', 'modality_id')
    op.create_table('partners',
    sa.Column('partner_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partner_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('partner_id', name=op.f('partners_pkey')),
    sa.UniqueConstraint('partner_name', name=op.f('partners_partner_name_key'))
    )
    # ### end Alembic commands ###
