"""add_process_chain_and_views

Revision ID: f9d8e7c6b5a4
Revises: a1b2c3d4e5f6
Create Date: 2025-07-16 11:30:25.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9d8e7c6b5a4'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

# SQL definitions for the views
# Using functions to avoid formatting issues and ensure readability
def create_all_product_requirements_view():
    return """
    CREATE OR REPLACE VIEW all_product_requirements AS
    SELECT 
        p.product_id,
        mr.required_capability_id,
        mr.requirement_level,
        mr.is_critical,
        'inherited' as requirement_source,
        m.modality_name,
        mc.capability_name
    FROM products p 
    JOIN modality_requirements mr ON p.modality_id = mr.modality_id
    JOIN modalities m ON p.modality_id = m.modality_id
    JOIN manufacturing_capabilities mc ON mr.required_capability_id = mc.capability_id
    UNION ALL
    SELECT 
        pr.product_id,
        pr.required_capability_id,
        pr.requirement_level,
        pr.is_critical,
        'specific' as requirement_source,
        m.modality_name,
        mc.capability_name
    FROM product_requirements pr
    JOIN products p ON pr.product_id = p.product_id
    LEFT JOIN modalities m ON p.modality_id = m.modality_id
    JOIN manufacturing_capabilities mc ON pr.required_capability_id = mc.capability_id;
    """

def create_product_complexity_summary_view():
    return """
    CREATE OR REPLACE VIEW product_complexity_summary AS
    SELECT 
        p.product_id,
        p.product_name,
        p.modality_id,
        m.modality_name,
        p.expected_launch_year,
        COUNT(apr.required_capability_id) as total_requirements,
        COALESCE(SUM(mc.complexity_weight), 0) as complexity_score,
        COUNT(CASE WHEN apr.is_critical THEN 1 END) as critical_requirements
    FROM products p
    LEFT JOIN modalities m ON p.modality_id = m.modality_id
    LEFT JOIN all_product_requirements apr ON p.product_id = apr.product_id
    LEFT JOIN manufacturing_capabilities mc ON apr.required_capability_id = mc.capability_id
    GROUP BY p.product_id, p.product_name, p.modality_id, m.modality_name, p.expected_launch_year;
    """

def drop_views():
    return """
    DROP VIEW IF EXISTS product_complexity_summary;
    DROP VIEW IF EXISTS all_product_requirements;
    """


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Process Chain Tables
    op.create_table('process_stages',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('stage_category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('stage_id'),
    sa.UniqueConstraint('stage_name')
    )
    op.create_table('process_templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['modalities.modality_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('product_process_overrides',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('override_type', sa.String(length=50), nullable=True),
    sa.Column('additional_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['process_stages.stage_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'stage_id')
    )
    op.create_table('template_stages',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('base_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['process_stages.stage_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['process_templates.template_id'], ),
    sa.PrimaryKeyConstraint('template_id', 'stage_id')
    )
    op.create_index(op.f('idx_template_stages_lookup'), 'template_stages', ['template_id', 'stage_id'], unique=False)

    # Update Existing Tables
    op.add_column('manufacturing_challenges', sa.Column('related_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('manufacturing_technologies', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.add_column('manufacturing_technologies', sa.Column('innovation_potential', sa.Text(), nullable=True))
    op.add_column('manufacturing_technologies', sa.Column('complexity_rating', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_technologies_stage_id', 'manufacturing_technologies', 'process_stages', ['stage_id'], ['stage_id'])

    # Create Strategic Views
    op.execute(create_all_product_requirements_view())
    op.execute(create_product_complexity_summary_view())

    # Create Performance Indexes
    op.create_index('idx_entity_capabilities_lookup', 'entity_capabilities', ['entity_id', 'capability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop Indexes
    op.drop_index('idx_entity_capabilities_lookup', table_name='entity_capabilities')

    # Drop Views
    op.execute(drop_views())

    # Revert Table Updates
    op.drop_constraint('fk_technologies_stage_id', 'manufacturing_technologies', type_='foreignkey')
    op.drop_column('manufacturing_technologies', 'complexity_rating')
    op.drop_column('manufacturing_technologies', 'innovation_potential')
    op.drop_column('manufacturing_technologies', 'stage_id')
    op.drop_column('manufacturing_challenges', 'related_capabilities')

    # Drop Process Chain Tables
    op.drop_index(op.f('idx_template_stages_lookup'), table_name='template_stages')
    op.drop_table('template_stages')
    op.drop_table('product_process_overrides')
    op.drop_table('process_templates')
    op.drop_table('process_stages')
    # ### end Alembic commands ###